[package]
name = "robson"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
debug = 1
[dependencies]
crossterm = "0.23.2"
robson_compiler = { path = "./robson_compiler" }
